<a href="https://colab.research.google.com/github/prof-aro-ufm/cs070-2026/blob/labs/reports/lab0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Writing File(s)

---

# CSV File(s)

In [ ]:
import csv

# Define the file name
file_name = 'sample_data.csv'

# Define the header and some sample data
header = ['Name', 'Age', 'City']
data = [
    ['Alice', 30, 'New York'],
    ['Bob', 24, 'Los Angeles'],
    ['Charlie', 35, 'Chicago']
]

# Write the data to the CSV file
with open(file_name, 'w', newline='') as csvfile:
    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(header) # Write the header
    csv_writer.writerows(data)  # Write the data rows

print(f"CSV file '{file_name}' created successfully.")

# You can verify its content by running:
# !cat sample_data.csv

CSV file 'sample_data.csv' created successfully.

In [ ]:
import csv

with open(sample_data.csv, 'w', newline='') as csvfile:
    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(header)
    csv_writer.writerows(data)

In [ ]:
!cat sample_data.csv

Name,Age,City
Alice,30,New York
Bob,24,Los Angeles
Charlie,35,Chicago

In [ ]:
!ls content

ls: cannot access 'content': No such file or directory

# JSON File(s)

In [ ]:
import json

# Define the file name
json_file_name = 'sample_data.json'

# Define some sample data
data = [
    {'Name': 'Alice', 'Age': 30, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 24, 'City': 'Los Angeles'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}
]

# Write the data to the JSON file
with open(json_file_name, 'w') as jsonfile:
    json.dump(data, jsonfile, indent=4)

print(f"JSON file '{json_file_name}' created successfully.")

JSON file 'sample_data.json' created successfully.

In [ ]:
# Display the content of the created JSON file
!cat sample_data.json

[
    {
        "Name": "Alice",
        "Age": 30,
        "City": "New York"
    },
    {
        "Name": "Bob",
        "Age": 24,
        "City": "Los Angeles"
    },
    {
        "Name": "Charlie",
        "Age": 35,
        "City": "Chicago"
    }
]

# TXT File(s)

In [ ]:
# Define the file name
txt_file_name = 'sample_data.txt'

# Define some sample content
content = "This is a sample text file.\nIt contains multiple lines of text.\nHello, world!"

# Write the content to the text file
with open(txt_file_name, 'w') as txtfile:
    txtfile.write(content)

print(f"Text file '{txt_file_name}' created successfully.")

Text file 'sample_data.txt' created successfully.

In [ ]:
# Display the content of the created text file
!cat sample_data.txt

This is a sample text file.
It contains multiple lines of text.
Hello, world!

# Reading File(s)

---

# Reading File(s) w/o Pandas

### Reading `sample_data.csv` without pandas

In [ ]:
import csv

file_name = 'sample_data.csv'

with open(file_name, 'r') as csvfile:
    csv_reader = csv.reader(csvfile)
    header = next(csv_reader)  # Read the header row
    data = []
    for row in csv_reader:
        data.append(row)

print("Header:", header)
print("Data (first 5 rows if available):", data[:5])

Header: ['Name', 'Age', 'City']
Data (first 5 rows if available): [['Alice', '30', 'New York'], ['Bob', '24', 'Los Angeles'], ['Charlie', '35', 'Chicago']]

In [ ]:
with open(sample_data.csv, 'r') as csvfile:
    csv_reader = csv.reader(csvfile)
    header = next(csv_reader)
    data = []
    for row in csv_reader:
        data.append(row)

### Reading `sample_data.json` without pandas

In [ ]:
import json

json_file_name = 'sample_data.json'

with open(json_file_name, 'r') as jsonfile:
    data = json.load(jsonfile)

print("Data (first 5 entries if available):", data[:5])

Data (first 5 entries if available): [{'Name': 'Alice', 'Age': 30, 'City': 'New York'}, {'Name': 'Bob', 'Age': 24, 'City': 'Los Angeles'}, {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}]

# Reading File(s) w/ Numpy

### TXT File(s)

In [ ]:
# Define the file name
txt_file_name = 'sample_data.txt'

# Define some sample content
content = "This is a sample text file.\nIt contains multiple lines of text.\nHello, world!"

# Write the content to the text file (if not already created)
with open(txt_file_name, 'w') as txtfile:
    txtfile.write(content)

print(f"Text file '{txt_file_name}' ensured to be created.")

# Now, read the content of the text file
with open(txt_file_name, 'r') as txtfile:
    read_content = txtfile.read()

print(f"\nContent of '{txt_file_name}':\n{read_content}")

Text file 'sample_data.txt' ensured to be created.

Content of 'sample_data.txt':
This is a sample text file.
It contains multiple lines of text.
Hello, world!

### JSON File(s)

In [ ]:
import json
import numpy as np

json_file_name = 'sample_data.json'

# Step 1: Read the JSON file into a Python list of dictionaries
with open(json_file_name, 'r') as jsonfile:
    data_from_json = json.load(jsonfile)

print(f"Data read from {json_file_name} (Python list of dicts):")
print(data_from_json)

# Step 2: Convert the list of dictionaries to a structured NumPy array
# First, define the dtype for the structured array based on the JSON structure
dtype = [('Name', 'U50'), ('Age', 'i4'), ('City', 'U50')]

# Create an empty structured array
numpy_json_array = np.empty(len(data_from_json), dtype=dtype)

# Populate the structured array
for i, item in enumerate(data_from_json):
    numpy_json_array[i]['Name'] = item['Name']
    numpy_json_array[i]['Age'] = item['Age']
    numpy_json_array[i]['City'] = item['City']

print(f"\nContent of {json_file_name} as a structured NumPy array:")
print(numpy_json_array)
print("Data type of the NumPy array:", numpy_json_array.dtype)

Data read from sample_data.json (Python list of dicts):
[{'Name': 'Alice', 'Age': 30, 'City': 'New York'}, {'Name': 'Bob', 'Age': 24, 'City': 'Los Angeles'}, {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}]

Content of sample_data.json as a structured NumPy array:
[('Alice', 30, 'New York') ('Bob', 24, 'Los Angeles')
 ('Charlie', 35, 'Chicago')]
Data type of the NumPy array: [('Name', '<U50'), ('Age', '<i4'), ('City', '<U50')]

### CSV File(s)

In [ ]:
import numpy as np

csv_file_name = 'sample_data.csv'

# Use np.genfromtxt to read the CSV file
# delimiter=',' specifies that values are separated by commas
# skip_header=1 skips the first row, which is assumed to be the header
# dtype=None allows NumPy to infer the data types of columns
# encoding='utf-8' is good practice for text files
csv_data = np.genfromtxt(csv_file_name, delimiter=',', skip_header=1, dtype=None, encoding='utf-8')

print(f"Content of {csv_file_name} using NumPy:")
print(csv_data)

# If you need to access columns by name, you can convert to a structured array
# You would typically define dtype with names explicitly for more complex CSVs
# For simple cases like this, it reads as a 2D array or structured array if dtypes vary

# To access header separately if needed:
# with open(csv_file_name, 'r') as f:
#     header = f.readline().strip().split(',')
# print("Header:", header)

Content of sample_data.csv using NumPy:
[('Alice', 30, 'New York') ('Bob', 24, 'Los Angeles')
 ('Charlie', 35, 'Chicago')]

# Reading File(s) w/ Pandas

### Reading `sample_data.csv` with pandas

In [ ]:
import pandas as pd

csv_file_name = 'sample_data.csv'
csv_df = pd.read_csv(csv_file_name)

print(f"Content of {csv_file_name}:")
display(csv_df.head())

Content of sample_data.csv:

      Name  Age         City
0    Alice   30     New York
1      Bob   24  Los Angeles
2  Charlie   35      Chicago

### Reading `sample_data.json` with pandas

In [ ]:
import pandas as pd

json_file_name = 'sample_data.json'
json_df = pd.read_json(json_file_name)

print(f"Content of {json_file_name}:")
display(json_df.head())

Content of sample_data.json:

      Name  Age         City
0    Alice   30     New York
1      Bob   24  Los Angeles
2  Charlie   35      Chicago

# Reading File(s) w/ Polars

In [ ]:
import polars as pl

# Read the CSV file with Polars
csv_file_name = 'sample_data.csv'
pl_csv_df = pl.read_csv(csv_file_name)

print(f"Content of {csv_file_name} using Polars:")
print(pl_csv_df)

Content of sample_data.csv using Polars:
shape: (3, 3)
┌─────────┬─────┬─────────────┐
│ Name    ┆ Age ┆ City        │
│ ---     ┆ --- ┆ ---         │
│ str     ┆ i64 ┆ str         │
╞═════════╪═════╪═════════════╡
│ Alice   ┆ 30  ┆ New York    │
│ Bob     ┆ 24  ┆ Los Angeles │
│ Charlie ┆ 35  ┆ Chicago     │
└─────────┴─────┴─────────────┘

In [ ]:
import polars as pl

# Read the JSON file with Polars
json_file_name = 'sample_data.json'
pl_json_df = pl.read_json(json_file_name)

print(f"Content of {json_file_name} using Polars:")
print(pl_json_df)

Content of sample_data.json using Polars:
shape: (3, 3)
┌─────────┬─────┬─────────────┐
│ Name    ┆ Age ┆ City        │
│ ---     ┆ --- ┆ ---         │
│ str     ┆ i64 ┆ str         │
╞═════════╪═════╪═════════════╡
│ Alice   ┆ 30  ┆ New York    │
│ Bob     ┆ 24  ┆ Los Angeles │
│ Charlie ┆ 35  ┆ Chicago     │
└─────────┴─────┴─────────────┘

# Reading File(s) w/ Pyspark

### Installing PySpark

In [ ]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (4.0.2)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark) (0.10.9.9)

### Initializing SparkSession

In [ ]:
from pyspark.sql import SparkSession

# Create a SparkSession
spark = SparkSession.builder.appName("ReadFiles").getOrCreate()

print("SparkSession created successfully.")

SparkSession created successfully.

### Reading `sample_data.csv` with PySpark

In [ ]:
csv_file_name = 'sample_data.csv'
# Read CSV file, inferSchema to detect data types, and header to use the first row as column names
spark_csv_df = spark.read.csv(csv_file_name, header=True, inferSchema=True)

print(f"Content of {csv_file_name} using PySpark:")
spark_csv_df.show()
spark_csv_df.printSchema()

Content of sample_data.csv using PySpark:
+-------+---+-----------+
|   Name|Age|       City|
+-------+---+-----------+
|  Alice| 30|   New York|
|    Bob| 24|Los Angeles|
|Charlie| 35|    Chicago|
+-------+---+-----------+

root
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- City: string (nullable = true)

### Reading `sample_data.json` with PySpark

In [ ]:
json_file_name = 'sample_data.json'
# Read JSON file, inferSchema to detect data types, and specify multiLine=True for JSON arrays
spark_json_df = spark.read.json(json_file_name, multiLine=True, inferSchema=True)

print(f"Content of {json_file_name} using PySpark:")
spark_json_df.show()
spark_json_df.printSchema()

Content of sample_data.json using PySpark:

AnalysisException: [UNSUPPORTED_FEATURE.QUERY_ONLY_CORRUPT_RECORD_COLUMN] The feature is not supported: Queries from raw JSON/CSV/XML files are disallowed when the
referenced columns only include the internal corrupt record column
(named `_corrupt_record` by default). For example:
`spark.read.schema(schema).json(file).filter($"_corrupt_record".isNotNull).count()`
and `spark.read.schema(schema).json(file).select("_corrupt_record").show()`.
Instead, you can cache or save the parsed results and then send the same query.
For example, `val df = spark.read.schema(schema).json(file).cache()` and then
`df.filter($"_corrupt_record".isNotNull).count()`. SQLSTATE: 0A000